<h1>Ocr Tasks</h1>
<table id="ocr-tasks">
    <thead>
        <tr>
            <?php foreach($this->paginator->getItem(0) as $key=>$val):?>
                <th>
                    <?php echo $key;?>

                </th>
            <?php endforeach;?>

        </tr>
    </thead>

    <tfoot>

    </tfoot>

    <tbody>
        <?php foreach($this->paginator as $task):?>
            <tr>
                <?php foreach($task as $key=>$val):?>
                    <?php if($key == 'resultUrl'):?>
                        
                    <?php else:?>
                        <td><?php echo $val;?></td>
                     <?php endif;?>
                <?php endforeach;?>

            </tr>
        <?php endforeach;?>

    </tbody>
</table>